=== XaquinAlves/1_Daw_Programacion_NB/Exame2aEvaluacion/src/resources/potter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="personaxes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="personaxe" type="tipoPersonaxe" maxOccurs="unbounded"/>
        <xs:element name="materias" type="tipoMaterias"/>
      </xs:sequence>
    </xs:complexType>
    <!-- unicidade do código da materia-->
    <xs:unique name="codMateria">
      <xs:selector xpath="materias/materia"/>
      <xs:field xpath="@codigo"/>
    </xs:unique>
    <!-- claves -->
    <xs:key name="codPersonaxe">
      <xs:selector xpath="personaxe/hogwarts"/>
      <xs:field xpath="codigo"/>
    </xs:key>
    <xs:keyref name="referenciaProfesorado" refer="codPersonaxe">
      <xs:selector xpath="materias/materia"/>
      <xs:field xpath="docente"/>
    </xs:keyref>
    <xs:keyref name="referenciaAlumnado" refer="codPersonaxe">
      <xs:selector xpath="materias/materia/alumno"/>
      <xs:field xpath="."/>
    </xs:keyref>
  </xs:element>
  <!-- tipoPersonaxe -->
  <xs:complexType name="tipoPersonaxe">
    <xs:sequence>
      <xs:element name="nome" type="xs:string"/>
      <xs:element name="hogwarts" type="tipoHogwarts" minOccurs="0"/>
      <xs:element name="caracteristicas" type="tipoCaracteristicas"/>
      <xs:element name="mascota" type="tipoMascota" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="protagonista" type="tipoProtagonista"/>
    </xs:sequence>
    <xs:attribute name="tipo" type="tipoTipoPersonaxe" default="maxica"/>
  </xs:complexType>
  <!--tipoHogwarts -->
  <xs:complexType name="tipoHogwarts">
    <xs:sequence>
      <xs:element name="codigo" type="tipoCodigoPersonaxe"/>
      <xs:element name="curso" type="xs:string" minOccurs="0"/>
      <xs:element name="quidditch" type="xs:string" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="casa" type="xs:string"/>
    <xs:attribute name="posto" type="tipoPosto" use="required"/>
  </xs:complexType>
  <!-- tipoMascota -->
  <xs:complexType mixed="true" name="tipoMascota">
    <xs:attribute name="animal" type="xs:string" use="required"/>
    <xs:attribute name="idade" type="xs:unsignedByte"/>
  </xs:complexType>
  <!-- tipoMaterias -->
  <xs:complexType name="tipoMaterias">
    <xs:sequence>
      <xs:element name="materia" type="tipoMateria" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <!-- tipoMateria -->
  <xs:complexType name="tipoMateria">
    <xs:sequence>
      <xs:element name="nome" type="xs:string"/>
      <xs:element name="curso" type="tipoCurso"/>
      <xs:element name="docente" type="xs:string"/>
      <xs:element name="alumno" type="xs:string" maxOccurs="50"/>
    </xs:sequence>
    <xs:attribute name="codigo" type="tipoCodigoMateria" use="required"/>
  </xs:complexType>
  <!-- tipoProtegonista -->
  <xs:complexType name="tipoProtagonista">
    <xs:attribute name="valor" type="xs:boolean" use="required"/>
  </xs:complexType>
  <!-- restriccións -->
  <!-- O atributo tipo de personaxe será opcional e poderá tomar os valores maxica, muggle, elfo ou outros -->
  <xs:simpleType name="tipoTipoPersonaxe">
    <xs:restriction base="xs:string">
      <xs:enumeration value="maxica"/>
      <xs:enumeration value="muggle"/>
      <xs:enumeration value="elfo"/>
      <xs:enumeration value="outros"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- posto é obrigatorio e pode tomar unicamente os valores alumnado, profesorado, direccion, pantasma, conserxería ou outro. -->
  <xs:simpleType name="tipoPosto">
    <xs:restriction base="xs:string">
      <xs:enumeration value="alumnado"/>
      <xs:enumeration value="profesorado"/>
      <xs:enumeration value="direccion"/>
      <xs:enumeration value="pantasma"/>
      <xs:enumeration value="conserxeria"/>
      <xs:enumeration value="outro"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- O elemento curso tomará un valor enteiro de 1 a 7 -->
  <xs:simpleType name="tipoCurso">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="7"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- codigo de alumnado e profesorado -->
  <xs:simpleType name="tipoCodigoPersonaxe">
    <xs:restriction base="xs:string">
      <xs:pattern value="[AP]((-[0-9]{4}){2}|(-[0-9]{3}))"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- código da materia -->
  <xs:simpleType name="tipoCodigoMateria">
    <xs:restriction base="xs:string">
      <xs:pattern value="MM-[1-7][0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- tipoCaracteristicas-->
  <xs:simpleType name="tipoCaracteristicas">
    <xs:restriction base="xs:string">
      <xs:maxLength value="150"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== XaquinAlves/1_Daw_Programacion_NB/Exame2aEvaluacion/src/resources/potter.xml
<?xml version="1.0" encoding="UTF-8"?>
<personaxes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="potter.xsd">
  <personaxe tipo="maxica">
    <nome>Harry Potter</nome>
    <hogwarts casa="Griffindor" posto="alumnado">
      <codigo>A-1992-0001</codigo>
      <curso>3</curso>
      <quidditch>Buscador</quidditch>
    </hogwarts>
    <caracteristicas>Cicatriz en forma de raio na fronte.</caracteristicas>
    <mascota animal="curuxa" idade="3">Hedwig</mascota>
    <protagonista valor="true"/>
  </personaxe>
  
  <personaxe tipo="maxica">
    <nome>Hermione Granger</nome>
    <hogwarts casa="Griffindor" posto="alumnado">
      <codigo>A-1992-0002</codigo>
      <curso>3</curso>
    </hogwarts>
    <caracteristicas>Moi observadora e boa estudante.</caracteristicas>
    <mascota animal="gata">Crookshanks</mascota>
    <protagonista valor="true"/>
  </personaxe>
  
  <personaxe tipo="maxica">
    <nome>Ron Weasley</nome>
    <hogwarts casa="Griffindor" posto="alumnado">
    <codigo>A-1992-0003</codigo>
      <curso>3</curso>
    </hogwarts>
    <caracteristicas>Pelo roxo. Ten medo ás arañas.</caracteristicas>
    <mascota animal="rata" idade="10">Scabbers</mascota>
    <protagonista valor="true"/>
  </personaxe>
  
  <personaxe>
    <nome>Ginny Weasley</nome>
    <hogwarts casa="Griffindor" posto="alumnado">
      <codigo>A-1993-0001</codigo>
      <curso>2</curso>
    </hogwarts>
    <caracteristicas>Pelo roxo.</caracteristicas>
    <protagonista valor="false"/>
  </personaxe>  
  
  <personaxe tipo="muggle">
    <nome>Dudley Dursley</nome>
    <caracteristicas>Maleducado.</caracteristicas>
    <protagonista valor="false"/>
  </personaxe>
  
  <personaxe tipo="elfo">
    <nome>Dobby</nome>
    <caracteristicas>Viste con farrapos.</caracteristicas>
    <protagonista valor="false"/>
  </personaxe>
  
  <personaxe tipo="maxica">
    <nome>Albus Dumbledore</nome>
    <hogwarts posto="direccion">
      <codigo>P-001</codigo>
    </hogwarts>
    <caracteristicas>Longa barba.</caracteristicas>
    <mascota animal="fénix">Fawkes</mascota>
    <protagonista valor="false"/>
  </personaxe>
  
  <personaxe>
    <nome>Minerva McGonagall</nome>
    <hogwarts casa="Griffindor" posto="profesorado">
      <codigo>P-002</codigo>
    </hogwarts>
    <caracteristicas>Moi estrita.</caracteristicas>
    <protagonista valor="false"/>
  </personaxe>
  
    <personaxe>
    <nome>Severus Snape</nome>
    <hogwarts casa="Slytherin" posto="profesorado">
      <codigo>P-003</codigo>
    </hogwarts>
    <caracteristicas>Apariencia escura.</caracteristicas>
    <protagonista valor="false"/>
  </personaxe>
  
  <personaxe tipo="maxica">
    <nome>Draco Malfoy</nome>
    <hogwarts casa="Slytherin" posto="alumnado">
      <codigo>A-1992-0004</codigo>
      <curso>3</curso>
    </hogwarts>
    <caracteristicas>Inimigo de Harry Potter.</caracteristicas>
    <protagonista valor="false"/>
  </personaxe>
  
  <materias>
    <materia codigo="MM-401">
      <nome>Transformacións 4</nome>
      <curso>4</curso>
      <docente>P-002</docente>
      <alumno>A-1992-0001</alumno>
      <alumno>A-1992-0002</alumno>
      <alumno>A-1992-0003</alumno>
      <alumno>A-1992-0004</alumno>
    </materia>
    
    <materia  codigo="MM-402">
      <nome>Pocións 4</nome>
      <curso>4</curso>
      <docente>P-003</docente>
      <alumno>A-1992-0001</alumno>
      <alumno>A-1992-0002</alumno>
      <alumno>A-1992-0003</alumno>
      <alumno>A-1992-0004</alumno>
    </materia>
    
    <materia codigo="MM-301">
      <nome>Transformacións 3</nome>
      <curso>3</curso>
      <docente>P-002</docente>
      <alumno>A-1993-0001</alumno>
    </materia>
  </materias>
</personaxes>
